local async = require 'async'

async.process.spawn('th', {'-e','while true do a=1 end'}, function(process)
   print('spawned process: ' .. process.pid)
   process.onexit(function(status, signal)
      print('process: ' .. process.pid .. ' exit with status/signal: ' .. status .. ', ' .. signal)
   end)
   process.stdout.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
   process.kill()
end)

async.process.exec('ls', {'-l'}, function(result, code)
   print('ls output:')
   io.write(result)
   print('ls terminated with code: ' .. code)
end)

async.process.spawn('th', {'-e','require "sys" a = io.read("*line") print(a) for i = 1,10 do sys.sleep(1) print(10) end'}, function(process)
   print('spawned process: ' .. process.pid)
   process.stdout.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
   process.stderr.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
   process.stdin.write('go\n')
end)

async.go()
