local async = require 'async'

async.process.spawn('th', {'-e','while true do a=1 end'}, function(process)
   print('spawned process: ' .. process.pid)
   process.onexit(function(status, signal)
      print('process: ' .. process.pid .. ' exit with status/signal: ' .. status .. ', ' .. signal)
   end)
   process.stdout.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
   process.kill()
end)

async.process.exec('ls', {'-l'}, function(result, code)
   print('ls output:')
   io.write(result)
   print('ls terminated with code: ' .. code)
end)

async.process.spawn('lua', {'-e','for i = 1,10 do print(10) end error("test error")'}, function(process)
   print('spawned process: ' .. process.pid)
   process.stdout.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
   process.stderr.ondata(function(data)
      io.write(''..process.pid.. ': ' .. data)
   end)
end)

async.go()
